### ISSUE TITLE
Поправить алгоритм

### ISSUE THREAD

**Issue by Kasiwadzaki** [ArtiWell/UnoSoft#1]
Добрый день, меня зовут Вадим, я разработчик компании Uno-Soft.

Есть несколько моментов:
1) В тестовом задании было условие что у программы должен быть входной агрумент, который представляет собой путь до файла с данными, а не заранее приготовленный файл. Это нужно чтобы без перекомпиляции программы запускать с любым файлом
2) При выполнении на базовом файле вылетает очень много ошибок:
```
java.lang.NumberFormatException: empty String
        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
        at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.base/java.lang.Float.parseFloat(Float.java:476)
        at com.example.unosoft.UnoSoft.convertString(UnoSoft.java:123)
        at com.example.unosoft.UnoSoft.readFile(UnoSoft.java:93)
        at com.example.unosoft.UnoSoft.main(UnoSoft.java:16)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
```
Прошу поправить оба момента

**Comment by ArtiWell** [comment]
нет больше идей= (
